<?php
declare(strict_types=1);
namespace HybridTM\Enums;

/** Technology values as accepted by Threagile 1.x (-list-types). */
enum Technology: string {
    case Unknown = 'unknown-technology';
    case ClientSystem = 'client-system';
    case Browser = 'browser';
    case Desktop = 'desktop';
    case MobileApp = 'mobile-app';
    case DevopsClient = 'devops-client';
    case WebServer = 'web-server';
    case WebApplication = 'web-application';
    case ApplicationServer = 'application-server';
    case WebServiceRest = 'web-service-rest';
    case WebServiceSoap = 'web-service-soap';
    case Database = 'database';
    case FileServer = 'file-server';
    case LocalFileSystem = 'local-file-system';
    case Erp = 'erp';
    case Cms = 'cms';
    case SearchIndex = 'search-index';
    case SearchEngine = 'search-engine';
    case ServiceRegistry = 'service-registry';
    case ReverseProxy = 'reverse-proxy';
    case LoadBalancer = 'load-balancer';
    case Waf = 'waf';
    case Ids = 'ids';
    case Ips = 'ips';
    case BuildPipeline = 'build-pipeline';
    case SourcecodeRepository = 'sourcecode-repository';
    case ArtifactRegistry = 'artifact-registry';
    case CodeInspectionPlatform = 'code-inspection-platform';
    case Monitoring = 'monitoring';
    case LdapServer = 'ldap-server';
    case IdentityProvider = 'identity-provider';
    case IdentityStoreLdap = 'identity-store-ldap';
    case IdentityStoreDatabase = 'identity-store-database';
    case ContainerPlatform = 'container-platform';
    case BatchProcessing = 'batch-processing';
    case EventListener = 'event-listener';
    case MessageQueue = 'message-queue';
    case StreamProcessing = 'stream-processing';
    case ServiceMesh = 'service-mesh';
    case DataLake = 'data-lake';
    case ReportEngine = 'report-engine';
    case Ai = 'ai';
    case MailServer = 'mail-server';
    case Vault = 'vault';
    case Hsm = 'hsm';
    case Scheduler = 'scheduler';
    case Mainframe = 'mainframe';
    case BlockStorage = 'block-storage';
    case Gateway = 'gateway';
    case IoTDevice = 'iot-device';
    case Function = 'function';
    case Tool = 'tool';
    case Cli = 'cli';
    case Library = 'library';
    case Task = 'task';
    case EjbSessionBean = 'ejb';
    case BigDataPlatform = 'big-data-platform';
}
